version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1
  path-filter: mkusaka/path-filter@dev:1e73b3d4ef688e844f739d049ee330b398612c5d

filters: &filters
  tags:
    only: /.*/

jobs:
  runcheck:
    docker:
      - image: cimg/base:2022.04
    steps:
      - path-filter/greet:
          to: filter

workflows:
  lint-pack:
    jobs:
      - runcheck
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters: *filters
      - orb-tools/publish:
          orb-name: mkusaka/path-filter
          vcs-type: << pipeline.project.type >>
          requires:
            [orb-tools/lint, orb-tools/review, orb-tools/pack, shellcheck/check]
          # Use a context to hold your publishing token.
          context: orb-publishing
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters: *filters
