version: 2.1
orbs:
  path-filter: mkusaka/path-filter@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

commands:
  check_result:
    parameters:
      filter_type:
        type: string
        default: continue
      path:
        type: string
        default: ''
      base_revision:
        type: string
        default: main
      head_revision:
        type: string
        default: HEAD
    steps:
      - run:
          name: check result << parameters.filter_type >>
          environment:
            FILTER_BASE_REVISION: << parameters.base_revision >>
            FILTER_HEAD_REVISION: << parameters.head_revision >>
            FILTER_REMOTE: << pipeline.project.git_url >>
            FILTER_PATH: << parameters.path >>
            FILTER_TYPE: << parameters.filter_type >>
          command: |
            set -x
            if [ "$FILTER_TYPE" == "continue" ]; then
              if ! git diff "$FILTER_BASE_REVISION".."$FILTER_HEAD_REVISION" --name-only | grep -q -E "$FILTER_PATH"; then
                echo expected unreached here, type: "$FILTER_TYPE"
                exit 1
              fi
            fi

  shallow_checkout:
    parameters:
      depth:
        type: integer
        default: 1
    steps:
      - run:
          name: shallow checkout
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            if [ "<< parameters.depth >>" -gt 0 ]; then
              git clone --depth << parameters.depth >> "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH" .
            else
              git clone "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH" .
            fi

jobs:
    # Create a job to test the commands of your orbs.
    # You may want to add additional validation steps to ensure the commands are working as expected.
    command-continue:
      parameters:
        depth:
          type: integer
          default: 1
        base_revision:
          type: string
          default: main
        head_revision:
          type: string
          default: HEAD
      docker:
        - image: cimg/base:current
      steps:
        - shallow_checkout:
            depth: << parameters.depth >>
        # Run your orb's commands to validate them.
        - path-filter/continue:
            path: .circleci/.*
            base_revision: << parameters.base_revision >>
            head_revision: << parameters.head_revision >>
        - check_result:
            path: .circleci/.*
            base_revision: << parameters.base_revision >>
            head_revision: << parameters.head_revision >>
            filter_type: continue
    command-stop:
      parameters:
        depth:
          type: integer
          default: 1
        base_revision:
          type: string
          default: main
        head_revision:
          type: string
          default: HEAD
      docker:
        - image: cimg/base:current
      steps:
        - shallow_checkout:
            depth: << parameters.depth >>
        # Run your orb's commands to validate them.
        - path-filter/stop:
            path: .circleci/.*
            base_revision: << parameters.base_revision >>
            head_revision: << parameters.head_revision >>
        - check_result:
            path: .circleci/.*
            base_revision: << parameters.base_revision >>
            head_revision: << parameters.head_revision >>
            filter_type: continue
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-continue:
          matrix:
            parameters:
              depth:
                - 1
                - 0
              base_revision:
                - << pipeline.git.base_revision >>
                - main
                - HEAD
              head_revision:
                - << pipeline.git.revision >>
                - main
                - HEAD
          filters: *filters
      - command-stop:
          matrix:
            parameters:
              depth:
                - 1
                - 0
              base_revision:
                - << pipeline.git.base_revision >>
                - main
                - HEAD
              head_revision:
                - << pipeline.git.revision >>
                - main
                - HEAD
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: mkusaka/path-filter
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-continue
            - command-stop
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
